"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import on_sdk
from on_sdk.api.organizations_api import OrganizationsApi  # noqa: E501


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_organization_api_organizations_post(self):
        """Test case for create_organization_api_organizations_post

        Create Organization  # noqa: E501
        """
        pass

    def test_read_organization_api_organizations_organization_id_get(self):
        """Test case for read_organization_api_organizations_organization_id_get

        Read Organization  # noqa: E501
        """
        pass

    def test_read_organizations_api_organizations_get(self):
        """Test case for read_organizations_api_organizations_get

        Read Organizations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
