"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import on_sdk
from on_sdk.model.project_create import ProjectCreate


class TestProjectCreate(unittest.TestCase):
    """ProjectCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectCreate(self):
        """Test ProjectCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
