"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import on_sdk
from on_sdk.api.auth_api import AuthApi  # noqa: E501


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_jwt_login_auth_jwt_login_post(self):
        """Test case for auth_jwt_login_auth_jwt_login_post

        Auth:Jwt.Login  # noqa: E501
        """
        pass

    def test_auth_jwt_logout_auth_jwt_logout_post(self):
        """Test case for auth_jwt_logout_auth_jwt_logout_post

        Auth:Jwt.Logout  # noqa: E501
        """
        pass

    def test_register_register_auth_register_post(self):
        """Test case for register_register_auth_register_post

        Register:Register  # noqa: E501
        """
        pass

    def test_reset_forgot_password_auth_forgot_password_post(self):
        """Test case for reset_forgot_password_auth_forgot_password_post

        Reset:Forgot Password  # noqa: E501
        """
        pass

    def test_reset_reset_password_auth_reset_password_post(self):
        """Test case for reset_reset_password_auth_reset_password_post

        Reset:Reset Password  # noqa: E501
        """
        pass

    def test_verify_request_token_auth_request_verify_token_post(self):
        """Test case for verify_request_token_auth_request_verify_token_post

        Verify:Request-Token  # noqa: E501
        """
        pass

    def test_verify_verify_auth_verify_post(self):
        """Test case for verify_verify_auth_verify_post

        Verify:Verify  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
