"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import on_sdk
from on_sdk.model.error_model import ErrorModel


class TestErrorModel(unittest.TestCase):
    """ErrorModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorModel(self):
        """Test ErrorModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
