"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import on_sdk
from on_sdk.api.needs_api import NeedsApi  # noqa: E501


class TestNeedsApi(unittest.TestCase):
    """NeedsApi unit test stubs"""

    def setUp(self):
        self.api = NeedsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_need_api_needs_post(self):
        """Test case for create_need_api_needs_post

        Create Need  # noqa: E501
        """
        pass

    def test_read_items_api_needs_get(self):
        """Test case for read_items_api_needs_get

        Read Items  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
