"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import on_sdk
from on_sdk.model.body_reset_forgot_password_auth_forgot_password_post import BodyResetForgotPasswordAuthForgotPasswordPost


class TestBodyResetForgotPasswordAuthForgotPasswordPost(unittest.TestCase):
    """BodyResetForgotPasswordAuthForgotPasswordPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyResetForgotPasswordAuthForgotPasswordPost(self):
        """Test BodyResetForgotPasswordAuthForgotPasswordPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyResetForgotPasswordAuthForgotPasswordPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
