"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import on_sdk
from on_sdk.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_current_user_users_me_get(self):
        """Test case for users_current_user_users_me_get

        Users:Current User  # noqa: E501
        """
        pass

    def test_users_current_user_users_me_patch(self):
        """Test case for users_current_user_users_me_patch

        Users:Current User  # noqa: E501
        """
        pass

    def test_users_user_users_id_delete(self):
        """Test case for users_user_users_id_delete

        Users:User  # noqa: E501
        """
        pass

    def test_users_user_users_id_get(self):
        """Test case for users_user_users_id_get

        Users:User  # noqa: E501
        """
        pass

    def test_users_user_users_id_patch(self):
        """Test case for users_user_users_id_patch

        Users:User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
