"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import on_sdk
from on_sdk.model.user_update import UserUpdate


class TestUserUpdate(unittest.TestCase):
    """UserUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserUpdate(self):
        """Test UserUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
