"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import on_sdk
from on_sdk.model.body_verify_request_token_auth_request_verify_token_post import BodyVerifyRequestTokenAuthRequestVerifyTokenPost


class TestBodyVerifyRequestTokenAuthRequestVerifyTokenPost(unittest.TestCase):
    """BodyVerifyRequestTokenAuthRequestVerifyTokenPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyVerifyRequestTokenAuthRequestVerifyTokenPost(self):
        """Test BodyVerifyRequestTokenAuthRequestVerifyTokenPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyVerifyRequestTokenAuthRequestVerifyTokenPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
