"""
    Open-Needs Server

    REST API Server of Open-Needs  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import on_sdk
from on_sdk.model.body_verify_verify_auth_verify_post import BodyVerifyVerifyAuthVerifyPost


class TestBodyVerifyVerifyAuthVerifyPost(unittest.TestCase):
    """BodyVerifyVerifyAuthVerifyPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyVerifyVerifyAuthVerifyPost(self):
        """Test BodyVerifyVerifyAuthVerifyPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodyVerifyVerifyAuthVerifyPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
